openapi: 3.0.0
info:
  title: Stopcovid19 Submission Web API
  description: |
    API for case submission on the stopcovid19 web front-end
  version: 0.1.0

servers:
  - url: https://api.stopcovid19.org/v1/

paths:
  /cases:
    get:
      summary: Return a list of cases
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "204":
          description: No content
        "403":
          description: Forbidden
        "503":
          description: Server Error
    post:
      summary: Create a Case
      responses:
        "201":
          description: Created

    put:
      summary: Update a Case
      responses:
        "200":
          description: Ok
  /cases/{id}:
    get:
      summary: Retrun a Specific Case
      parameters:
        - name: id
          in: path
          schema:
            type: string
